### ISSUE TITLE
Notify on telegram side when whatsapp requires auth

### ISSUE THREAD

**Issue by NicKoehler** [akshettrj/watgbridge#23]
I installed this on a Raspberry Pi 4 and set up a service to run it. Sometimes, the application asks for the QR code again, but it's hard to notice since I wasn't checking the service, and I have no way to do so without connecting to the Raspberry Pi to check if the service is asking for the QR code.

Is it possible to add a notification on the Telegram side when WhatsApp isn't authenticated correctly to make it more noticeable?

Thanks in advance for your great job!

**Comment by akshettrj** [comment]
Yeah, it might be possible. I will look into it

Did you switch off your original WhatsApp device? Because I think WhatsApp wants the primary device to come online every few days

**Comment by akshettrj** [comment]
It would make my task easier if you could answer some questions for me:

1. Does the QR code reappear after the bot restarts (which happens automatically every 24 hours if you are using the provided systemd service file), or is the QR code emitted during a running instance as well?

2. If it happens during a running instance, can you add some debugging statements [in line 32](https://github.com/akshettrj/watgbridge/blob/main/whatsapp/handlers.go#L32) to check what events are emitted when this happens?

Maybe add `fmt.Println(reflect.TypeOf(evt))` in line 32

**Comment by NicKoehler** [comment]
I don't know if is stopping after restarting or while running, how do I check this?

**Comment by NicKoehler** [comment]
It just prints the qr code, no errors

**Comment by NicKoehler** [comment]
Thank you very much for this update!
