### ISSUE TITLE
Support for some sticker formats

### ISSUE THREAD

**Issue by akshettrj** [akshettrj/watgbridge#8]
Currently, all types of stickers are not supported. Support for them will need some tinkering to be done

**From WhatsApp side**
- Animated stickers (WebP) are not supported

**From Telegram side**
- Video stickers are not supported

**Comment by yshalsager** [comment]
Telegram animated stickers can be converted to gif, check out [this project](https://github.com/ed-asriyan/tgs-to-gif).

**Comment by akshettrj** [comment]
Hi @yshalsager, I forgot to close this issue. I have already added support for all sticker types
